### ISSUE TITLE
SMA is gestopt

### ISSUE THREAD

**Issue by Mintr0** [jghaanstra/sma.modbus#2]
Sinds de recente update 2.1.2 werkt mijn flow voor SMA niet meer??

**Comment by jghaanstra** [comment]
Ik heb wel wat meer informatie nodig.

Laat de action card een uitroep teken zien of een groen vinkje. Heb je de app al herstart, etc.

**Comment by Mintr0** [comment]
Er is geen communicatie mogelijk met de SMA convertor.

**Comment by jghaanstra** [comment]
Herstart de app.

**Comment by Mintr0** [comment]
![2019-05-11 23 03 47](https://user-images.githubusercontent.com/50521759/57574966-25104e80-7442-11e9-951d-525c675efbc9.jpg)
![2019-05-11 23 04 14](https://user-images.githubusercontent.com/50521759/57574968-3194a700-7442-11e9-9cee-d68648ce0bc5.jpg)
![Schermafdruk 2019-05-11 23 07 02](https://user-images.githubusercontent.com/50521759/57574980-50933900-7442-11e9-9087-08039c2a9f38.png)
![Schermafdruk 2019-05-11 23 06 41](https://user-images.githubusercontent.com/50521759/57574988-73255200-7442-11e9-8370-d1a5ab35fe66.png)

**Comment by Mintr0** [comment]
het ipnummer in explorer is niet hetzelfde als op de converter. dit was altijd al zo. helaas is er geen communicatie tussen de app en converter.
heeft in het verleden prima gewerkt.

**Comment by jghaanstra** [comment]
Zorg ervoor dat je in je router een statisch IP adres toewijst aan je de SMA Speedwire en wijzig in Homey het IP adres van de omvormer naar hetzelfde IP. Dit heeft niks met mijn app of firmware 2.1.2 te maken maar wordt veroorzaakt door je eigen instellingen.

**Comment by Mintr0** [comment]
![Schermafdruk 2019-05-11 23 56 48](https://user-images.githubusercontent.com/50521759/57575327-905d1f00-7448-11e9-9323-4b09eb586c0c.png)
![2019-05-11 23 54 10](https://user-images.githubusercontent.com/50521759/57575330-9fdc6800-7448-11e9-96e5-2d175766161e.jpg)

**Comment by Mintr0** [comment]
Nog geen communicatie.

**Comment by jghaanstra** [comment]
Ik heb geen idee wat er aan de hand is maar de sma app werkt prima met firmware 2.1.2 dus dat is het probleem niet. Dat het ip in Sunny Explorer niet overeenkomt met het daadwerkelijke ip adres op het netwerk zal vast met de oorzaak te maken hebben. Ik zie ik dat de netwerk scan bij de omvormer geen Mac adres laat zien wat ik vreemd is. Dus ik zou eens proberen of je de speedwire kan forceren de netwerk instellingen te laten bijwerken door deze te editten en weer terug te zetten naar automatisch. En na elke wijziging de sma app te herstarten. Iets anders wat je kan doen is de sma app runnen vanaf de command line en aan de hand van de logging daar kijken wat er aan de hand is.

**Comment by Mintr0** [comment]
![Schermafdruk 2019-05-12 09 33 13](https://user-images.githubusercontent.com/50521759/57580089-74d43180-74a5-11e9-88f3-00adfac45c93.png)
![Schermafdruk 2019-05-12 11 08 56](https://user-images.githubusercontent.com/50521759/57580169-72bea280-74a6-11e9-8dcb-a9ba9561a8c8.png)
![Schermafdruk 2019-05-12 11 08 42](https://user-images.githubusercontent.com/50521759/57580173-77835680-74a6-11e9-95dd-06949a032719.png)

**Comment by Mintr0** [comment]
ik heb de instellingen op mijn SMA in dezelfde IP range gemaakt, helaas was toen alles van slag af niet meer te bereiken via web en niet via speedwire. heb de SMA gereset. blijft op de192.168. 0.170 terug komen. als ik mijn laptop in de 0 range set en ga pingen naar de SMA is deze niet bereikbaar.
allemaal onbegrijpelijk daar het weken prima heeft gewerkt met de huidige settings.

**Comment by Mintr0** [comment]
zojuist spontaan zonder wijzigingen de flow gaan werken???

**Comment by Mintr0** [comment]
Dank voor het meedenken.

**Comment by jghaanstra** [comment]
Mooi, veel plezier ermee.
