### ISSUE TITLE
App not compatible with Homey 2.5.2

### ISSUE THREAD

**Issue by asteman** [jghaanstra/sma.modbus#4]
Hi,
Seems like latest version of SMA App does not work on the latest 2.5.2 Homey version.

![image](https://user-images.githubusercontent.com/25367091/67428123-d87a9300-f5dd-11e9-901d-40806d1777f4.png)

\\ Andreas

**Comment by jghaanstra** [comment]
The lastest version of the app requires Homey firmware 3.x. You have three choices.

Switch to Homey experimental channel and install Homey firmware 3.x RCx
Wait till Homey firmware 3.x is released to the stable channel, my guess is this wont take long anymore
Install the previous release from the Shelly app using the command line as described here: https://community.athom.com/t/how-to-cli-install-method/198.
